#!/bin/sh

# This moves & snaps a floating window into position 1-9 on a HORIxVERT grid

HORI=3
VERT=3

bspc node focused -t floating

x=$(( $(xdpyinfo | grep "dimension" | cut -d" " -f7 | cut -d"x" -f1)/$HORI ))
y=$(( $(xdpyinfo | grep "dimension" | cut -d" " -f7 | cut -d"x" -f2)/$VERT ))

xdo resize -w $x -h $y
xdo move -x $(( (($1 - 1) % $HORI) * x )) -y $(( (($1 - 1) / $VERT) * y ))
