#!/bin/sh

# This moves & snaps a floating window into position 1-9 on a 3x3 grid

x=$(xdpyinfo | grep "dimension" | cut -d" " -f7 | cut -d"x" -f1)
y=$(xdpyinfo | grep "dimension" | cut -d" " -f7 | cut -d"x" -f2)

case $1 in
	1) x=0;								y=0;;
	2) x=$(echo "$x/3" | bc);		y=0;;
	3) x=$(echo "($x/3)*2" | bc);	y=0;;
	4) x=0;								y=$(echo "$y/3" | bc);;
	5) x=$(echo "$x/3" | bc);		y=$(echo "$y/3" | bc);;
	6) x=$(echo "($x/3)*2" | bc); y=$(echo "$y/3" | bc);;
	7) x=0;								y=$(echo "($y/3)*2" | bc);;
	8) x=$(echo "$x/3" | bc);		y=$(echo "($y/3)*2" | bc);;
	9) x=$(echo "($x/3)*2" | bc);	y=$(echo "($y/3)*2" | bc);;
esac

xdo move -x $x -y $y
